#!/bin/bash
set -e
set -u
set -o pipefail

for f in $(ls ./sample-data/*.json); do
    echo "sending: $f"
    curl \
        -X POST \
        -d @"$f" \
        -H 'Accept: application/json' \
        http://localhost:3000/packages
done

