resolver: lts-17.6
# Resolves hjsmin requiring language-javascript ==0.6, while the purescript
# compiler requires language-javascript ==0.7.
allow-newer: true

packages:
  - "."

extra-deps:
  - barrier-0.1.1
  - bytestring-trie-0.2.5.0
  - classy-prelude-yesod-1.5.0
  - language-javascript-0.7.0.0
  - purescript-0.14.3
  - purescript-cst-0.3.0.0

flags:
  pursuit:
    dev: true
  aeson-pretty:
    lib-only: true
  these:
    assoc: false
