#!/bin/bash
# Generates the LICENSE file and prints it to standard output.
# Example use:
#
#   ./license/generate
#

set -e              # exit on error
set -u              # exit on undefined variable
set -o pipefail     # propagate nonzero exit codes through pipelines

if ! which cabal-plan >/dev/null; then
    echo "$0: the program 'cabal-plan' is required." >&2
    echo "$0:   see Hackage: https://hackage.haskell.org/package/cabal-plan" >&2
    echo "$0:   repo: https://github.com/haskell-hvr/cabal-plan" >&2
    echo "$0: git clone the repo and run 'stack init && stack build --copy-bins --flag 'cabal-plan:license-report'" >&2
    echo "$0:   if there are any build issues, follow stack's suggestions about adding things to the 'extra-deps' field" >&2
    exit 1
fi

{
    cat license-generator/header.txt
    echo ""
    cabal-plan license-report exe:pursuit | sed 's/## /### /; s/# /## /;'
} > LICENSE
